name: CI Pipeline for Django

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          . venv/bin/activate
          python manage.py migrate  # This is necessary for tests if you have migrations

      - name: Run tests with pytest
        run: |
          . venv/bin/activate
          pytest  # Use Django's test database

      - name: Notify on success
        if: success()
        run: echo "✅ All tests passed!"
      
      - name: Notify on failure
        if: failure()
        run: echo "❌ Some tests failed!"
