name: CI Pipeline for Django

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: code_mentor_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"  # Check if PostgreSQL is ready
          --health-interval=10s  # Check readiness every 10 seconds
          --health-timeout=5s  # Timeout for readiness check
          --health-retries=5  # Retry checks 5 times

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up the Python environment
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |  # Run commands in the shell
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install project dependencies

      - name: Run tests
        env:  # Set environment variables for tests
          DATABASE_HOST: localhost  # Database host
          DATABASE_NAME: code_mentor_db  # Database name
          DATABASE_PORT: 5432  # Database port
          DATABASE_USER: postgres  # Database username
          DATABASE_PASSWORD: postgres  # Database password
        run: |  # Run commands in the shell
          sleep 10  # Wait for PostgreSQL to start (optional)
          python manage.py migrate  # Run database migrations
          pytest  # Run the tests
